### ISSUE TITLE
fsevents: unsupported platform

### ISSUE THREAD

**Issue by mgjuhler** [vlakreeh/csgo-heatmap-generator#4]
Hi, 

I am trying to get this running on windows 10 pro with node version 10.15.3.
when i am doing a "npm install --only=dev" i get the following error:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN csgo-heatmap-generator@1.0.0 No repository field.
```

Would it be a better idea to run it on a linux dist? ubuntu or like?

**Comment by mgjuhler** [comment]
I have now tried both on windows 10 and on ubuntu 18.04 and on both are my heatmaps blank .. what am i doing wrong?

**Comment by mgjuhler** [comment]
Mjellow?

**Comment by mgjuhler** [comment]
noting?

**Comment by zebp** [comment]
I'm so sorry, I didn't see this issue. I get the same error on my arch linux installation, I don't know what changed to cause this to happen. When trying to use the program I'm getting errors spat out by demofile left and right. I'll try to investigate today.

**Comment by mgjuhler** [comment]
did you get the time to take a look on it?

**Comment by zebp** [comment]
Yes, but I was getting errors with demofile. I haven't had the time to debug it yet i'll get on it soon.

**Comment by zebp** [comment]
The project now works again for new demos, the `fsevents` package does not seem to be required. Closing.

**Comment by mgjuhler** [comment]
Its still not working.
Images is stil blank

Os: Ubuntu 18.04
NodeJS version: v10.16.3
  csgo-heatmap-generator': '1.0.0',
  npm: '6.9.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  modules: '64',
  napi: '4',
  nghttp2: '1.39.2',
  node: '10.16.3',
  openssl: '1.1.1c',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.28.0',
  v8: '6.8.275.32-node.54',
  zlib: '1.2.11' 

```
lanu@nodejs:~/heatmap$ npm run start

> csgo-heatmap-generator@1.0.0 start /home/lanu/heatmap
> babel-node --presets env app.js

Processing 1_lgod-1-bramming_de_cache.dem.
Processing 2_halstedhus-1-vesterblle-1_de_overpass.dem.
Processing 3_lgod-1-vesterblle-1_de_mirage.dem.
Processing de_cache-attacker with 147 points.
Processing de_cache-victim with 147 points.
Processing de_mirage-attacker with 187 points.
Processing de_mirage-victim with 187 points.
Processing de_overpass-attacker with 179 points.
Processing de_overpass-victim with 179 points.
Wrote de_cache-attacker heatmap.
Wrote de_cache-victim heatmap.
Wrote de_mirage-attacker heatmap.
Wrote de_mirage-victim heatmap.
Wrote de_overpass-attacker heatmap.
Wrote de_overpass-victim heatmap.
lanu@nodejs:~/heatmap$
```

![de_cache-deaths](https://user-images.githubusercontent.com/6578036/63214686-af401100-c11b-11e9-922b-8950e70ce5a8.png)
![de_cache-kills](https://user-images.githubusercontent.com/6578036/63214687-af401100-c11b-11e9-8f40-b4bb9465bf14.png)
![de_mirage-deaths](https://user-images.githubusercontent.com/6578036/63214688-af401100-c11b-11e9-91c0-b72fef8136f1.png)
![de_mirage-kills](https://user-images.githubusercontent.com/6578036/63214689-af401100-c11b-11e9-80dc-43f06e1b47f2.png)
![de_overpass-deaths](https://user-images.githubusercontent.com/6578036/63214690-af401100-c11b-11e9-88b6-520670491e0a.png)
![de_overpass-kills](https://user-images.githubusercontent.com/6578036/63214691-afd8a780-c11b-11e9-8f15-620124a21d27.png)

Demos used: https://ufile.io/q7hlp1pr

**Comment by zebp** [comment]
Strange, I didn't have any issues with my demos but I am experiencing your bug too. I'll debug this asap.

**Comment by zebp** [comment]
Just fixed it, I was incorrectly generating the overlay json files. This project has become a mess. I'll rewrite it soon and make sure it isn't as horribly broken.

**Comment by mgjuhler** [comment]
any news?
